# Generated by Django 5.1.2 on 2025-06-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_avatar_remove_user_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
