# Generated by Django 5.1.2 on 2025-06-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_town'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
